### ISSUE TITLE
data_loader.py is not working on Mac Arm M1 

### ISSUE THREAD

**Issue by JTG2020** [redislabs-training/ru204#35]
I followed required steps on Mac Arm M1 and unable to get data_loader.py script working. Getting below errors in virtual environment.

python3 data_loader.py --dir data/books 
Connecting to Redis at redis://localhost:6379
Deleting any existing JSON documents for RU204.
Dropping any existing search index.
Creating search index.
Traceback (most recent call last):
  File "/Users/akanse/redis-course/ru204/data_loader.py", line 42, in <module>
    r.ft(INDEX_NAME).create_index(
  File "/Users/akanse/redis-course/ru204/venv/lib/python3.9/site-packages/redis/commands/search/commands.py", line 139, in create_index
    return self.execute_command(*args)
  File "/Users/akanse/redis-course/ru204/venv/lib/python3.9/site-packages/redis/client.py", line 1238, in execute_command
    return conn.retry.call_with_retry(
  File "/Users/akanse/redis-course/ru204/venv/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/Users/akanse/redis-course/ru204/venv/lib/python3.9/site-packages/redis/client.py", line 1239, in <lambda>
    lambda: self._send_command_parse_response(
  File "/Users/akanse/redis-course/ru204/venv/lib/python3.9/site-packages/redis/client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/Users/akanse/redis-course/ru204/venv/lib/python3.9/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/Users/akanse/redis-course/ru204/venv/lib/python3.9/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'FT.CREATE', with args beginning with: 'idx:books' 'ON' 'JSON' 'PREFIX' '1' 'ru204:book:' 'SCORE' '1.0' 'SCHEMA' '$.author' 'AS' 'author' 'TEXT' 'WEIGHT' '1.0' 'SORTABL' 

Note that required modules successfully installed -
pip install -r requirements.txt 
Requirement already satisfied: async-timeout==4.0.2 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: Deprecated==1.2.13 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.2.13)
Requirement already satisfied: packaging==21.3 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (21.3)
Requirement already satisfied: pyparsing==3.0.9 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (3.0.9)
Requirement already satisfied: redis==4.3.4 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (4.3.4)
Requirement already satisfied: wrapt==1.14.1 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.14.1)

**Comment by simonprickett** [comment]
Are you using the correct Redis Stack instance of Redis... this suggests that you don't have RediSearch installed.  This course requires both RedisJSON and RediSearch and is best taken using Redis Stack which has these pre-configured:

> redis.exceptions.ResponseError: unknown command 'FT.CREATE', with args beginning with: 'idx:books' 'ON' 'JSON' 'PREFIX' '1' 'ru204📖' 'SCORE' '1.0' 'SCHEMA' '$.author' 'AS' 'author' 'TEXT' 'WEIGHT' '1.0' 'SORTABL'

**Comment by simonprickett** [comment]
Closing this as we are unable to replicate this -- it's working on the M1 Mac that we have access to and the issue looks more like an issue with not using the correct Redis container as the `FT.CREATE` command does not appear to exist.
