### ISSUE TITLE
Unable to load sample data using Docker

### ISSUE THREAD

**Issue by cmoel** [redislabs-training/ru204#55]
👋 Hello.

I'm having trouble loading the data using Docker. I've followed the instructions up until https://github.com/redislabs-training/ru204#load-the-sample-data-into-redis-and-create-the-search-index and, with the `redisu-ru204` Docker container running, running `python data_loader.py --dir data/books` results in this stack trace:

```
$ python data_loader.py --dir data/books
Connecting to Redis at redis://localhost:6379
Deleting any existing JSON documents for RU204.
Dropping any existing search index.
Creating search index.
Traceback (most recent call last):
  File "/Users/cmoel/Desktop/ru204/data_loader.py", line 41, in <module>
    r.ft(INDEX_NAME).create_index(
  File "/Users/cmoel/Desktop/ru204/venv/lib/python3.11/site-packages/redis/commands/search/commands.py", line 139, in create_index
    return self.execute_command(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmoel/Desktop/ru204/venv/lib/python3.11/site-packages/redis/client.py", line 1238, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmoel/Desktop/ru204/venv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/Users/cmoel/Desktop/ru204/venv/lib/python3.11/site-packages/redis/client.py", line 1239, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmoel/Desktop/ru204/venv/lib/python3.11/site-packages/redis/client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmoel/Desktop/ru204/venv/lib/python3.11/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmoel/Desktop/ru204/venv/lib/python3.11/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'FT.CREATE', with args beginning with: 'idx:books' 'ON' 'JSON' 'PREFIX' '1' 'ru204:book:' 'SCORE' '1.0' 'SCHEMA' '$.author' 'AS' 'author' 'TEXT' 'WEIGHT' '1.0' 'SORTABL'
```

The error is caused by [data_loader.py:41](https://github.com/redislabs-training/ru204/blob/main/data_loader.py#L41-L60).

I've inspected the `r` variable in `data_loader.py` and it appears to be connected to the correct database in the container. Is there something in particular I should try next?

**Comment by simonprickett** [comment]
Hi there - sorry for the slow response here.  Your Redis on 6379 doesn't have the search module installed so there is no `FT.CREATE` command:

```
redis.exceptions.ResponseError: unknown command 'FT.CREATE', with args beginning with: 'idx:books' 'ON' 'JSON' 'PREFIX' '1' 'ru204:book:' 'SCORE' '1.0' 'SCHEMA' '$.author' 'AS' 'author' 'TEXT' 'WEIGHT' '1.0' 'SORTABL'
```

This can be caused by having a different instance of Redis already running on 6379 when you start the Docker container.  This results in the code connecting to that Redis and trying to run commands against it that it doesn't support.

Please check for other containers running or instances of the `redis-server` binary running, and anything on port `6379`.  Close those down before running the course container and data loader, alternatively move the course container to expose Redis on another port by editing `docker-compose.yml` and and supplying the new port to the data loader.
